name: docker-manifest

on:
  workflow_run:
    workflows:
      - build-native-amd64
      - build-native-arm64
    types:
      - completed

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository }}:latest-amd64 \
            ghcr.io/${{ github.repository }}:latest-arm64

          docker manifest annotate ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository }}:latest-amd64 --arch amd64

          docker manifest annotate ghcr.io/${{ github.repository }}:latest \
            ghcr.io/htv/myapp:latest-arm64 --arch arm64

          docker manifest push ghcr.io/${{ github.repository }}:latest
